@host=https://localhost:7066

POST {{host}}/api/Authentications/UnBlockAppUser
Content-Type: application/json

# {
#  "userName": must
#  "identityNumber": must
#  "phone": must
#  "email": must
#  "newPassword": must
# }

{
  "userName": "string", 
  "temporaryPassword": "ByWy3yps",
  "newPassword": "strongPsswrd!123",
  "email": "string@str.com",
  "identityNumber": "12812322445", 
  "phone": "1234445566" 
}

# Response like below:
#{
#  "response": {
#    "token": "eyJ.asd..",
#    "email": "str@string.com"
#  },
#  "success": true,
#  "message": "Success",
#  "serverDate": "2024-01-18T00:29:44.8030844Z",
#  "referenceNo": "f76c3553-d58b-4760-ae30-601de17827b9"
#}
