@host=https://localhost:7066
@token=ey.JjLBw..

PUT {{host}}/api/Expenses/Update
Content-Type: application/json
Authorization: Bearer {{token}}

# userId: That is id value of the Updater of user. 

{
  "id": 1,
  "accessToken": "abc123xyz456",
  "userId": 2,
  "requestTimestamp": "2024-01-19T23:23:12.962Z",
  "amount": 100.23,
  "description": "Dinner with clients, at the !",
  "title": "Business Meal",
  "receiptPhotoUrl": "https://example.com/receipt123.jpg"
}

#Success response be like:

#{
#  "success": true,
#  "message": "1 is updated successfully!",
#  "serverDate": "2024-01-19T23:23:12.964Z",
#  "referenceNo": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
#}

