@host=https://localhost:7066
@id=1
@token=ey.JjLBw..

DELETE {{host}}/api/ExpenseApprovals/Delete/{{id}}
Authorization: Bearer {{token}}

#Success response be like:

#{
#  "success": true,
#  "message": "1 is deleted successfully!",
#  "serverDate": "2024-01-19T23:23:12.964Z",
#  "referenceNo": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
#}

